# For a test of the ConfigImpl class only
org.ujorm.testOnly=fileValue

# The first key in the sequence represents the primary key.
_org.ujorm.firstPropertyIsIdentifier = true;

# Batch size for the INSERT(default 512)
org.ujorm.insertBatchSize = 50;

# Maximum size of the cache in the ResultSet Mapper (default 512)
_org.ujorm.maxCacheSize = 512;

# Log is switched off.
org.ujorm.logSqlLevel = FINEST

# Enable quoting the SQL columns
_org.ujorm.enableSqlQuoting = true;

# Write a warning if the column is not a relation and has no JDBC mapping.
_org.ujorm.columnMappingWarning = true;

# Print warnings, if Connection autocommit is true in batch operations.
_org.ujorm.autoCommitWarned = true;